config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'posts#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :companies
  resources :posts, only: [:show, :new, :create, :index]  do
    resource :comments
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
        can :access, :rails_admin       # only allow admin users to access Rails Admin
        can :manage, :dashboard         # allow access to dashboard
      else
        can :read, :all
      end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  belongs_to :parent, optional: true, class_name: "Comment"
  validates_presence_of :body

  def comments
    Comment.where(commentable: commentable, parent_id: id)
  end
end

app/models/company.rb
class Company < ApplicationRecord
    validates_presence_of :name, :corporate_name, :cnpj, :address, :domain
    validates_uniqueness_of :cnpj, :domain
    validates :cnpj, format: { with: /[0-9]{2}\.?[0-9]{3}\.?[0-9]{3}\/?[0-9]{4}\-?[0-9]{2}/, message: 'formato aceito: **.***.***/****-**'}
    validates :cnpj, length: { is: 18 }
    has_many :users, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :body, :title
  belongs_to :user
  has_many :comments, as: :commentable
  validates_presence_of :body
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :name, :email, :password
  validates_uniqueness_of :email
  belongs_to :company
  has_many :comments
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    def create
        find_commentable()
        @comment = @commentable.comments.build(comment_params)
        @comment.save
        redirect_to @commentable
    end

    private 

    def comment_params
        params.require(:comment).permit(:body, :parent_id)
                                .merge(user_id: current_user.id)
    end  

    def find_commentable
        @commentable = Post.find_by_id(params[:post_id])
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
    
    def index
      @companies = Company.all
    end

    def new
      @company = Company.new
    end

    def show
      @company = Company.find(params[:id])
    end
    
    def edit
      @company = Company.find(params[:id])
    end

    def create
      @company = Company.new(company_params)
      if @company.save
        flash[:notice] = 'Company was successfully created.'
        redirect_to new_user_registration_path
      else
        render action: "new"
      end
    end

    def update
      if @company.update(company_params)
        redirect_to @company, notice: 'Company was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @video.destroy
      redirect_to root_path, notice: 'Video was successfully destroyed.'
    end

    private

    def company_params
        params.require(:company).permit(:name, :corporate_name, :cnpj, 
            :address, :domain)
    end
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_post, only: [:show, :edit, :update, :destroy]
  
    def index
      @pagy, @posts = pagy(Post.all)
    end
  
    def show
    end
  
    def new
      @post = Post.new
    end
  
    def edit
    end
  
    def create
      @post = Post.new(post_params)
      @post.user = current_user
        if @post.save
           redirect_to @post, notice: 'Post was successfully created.'
        else
           render :new
        end
    end
  
    def update
      if @post.update(post_params)
          redirect_to @post, notice: 'Post was successfully updated.' 
      else
          render :edit 
      end
    end
  
    def destroy
      @post.destroy
        redirect_to posts_url, notice: 'Post was successfully destroyed.' 
    end
  
    private
      def set_post
        @post = Post.find(params[:id])
      end
  
      def post_params
        params.require(:post)
            .permit(:body, :title, :user_id)
            
      end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private
  
    def sign_up_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :company_id, :admin)
    end
  
    def account_update_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/comments/_comment.html.erb
<div class="form-group col-md-6">
  <h4> <%= comment.body%> </h4>
  <h6>Autor: <%= comment.user.name%></h6>
</div>
<div class="form-group">
  <%= render partial: "comments/form", locals: { commentable: @post , parent_id: comment.id} %>
</div>

<ol>
  <%= render comment.comments %>
</ol>

app/views/comments/_form.html.erb
<%= form_with model: [commentable, Comment.new], local: true do |form| %>
  <% commentable.errors.full_messages.each do |message|%>
    <ul>
       <li><%= message%></li>
    </ul>
  <% end %>
    <%= form.text_area :body, class: "form-group form-control", placeholder: "Add Comment" %>
    <div class="form-row">
      <div class="form-group col-md-6">
        <%= form.hidden_field :parent_id, value: local_assigns[:parent_id] %>
      </div>
      <div class="form-group col-md-4"></div>
      <div class="form-group col-md-1">
        <%= form.submit 'Enviar', class:'btn btn-outline-secondary' %>
      </div>
    </div>
<% end %>

app/views/companies/new.html.erb
<body>
  <div class="container">
      <div class="row">
        <div class="col-lg-10 col-xl-9 mx-auto">
          <div class="card card-signin flex-row my-5">
            <div class="card-img-left d-none d-md-flex">
            </div>
            <div class="card-body">
              <% @company.errors.full_messages.each do |message|%>
               <ul>
                <ol class="text-center alert-danger"><%= message%></ol>
              </ul>
              <%end%>
              <h5 class="card-title text-center text-light bg-dark">New Company</h5>
              <%= form_with model: @company, local: true do |f|%>
                <div class="form-label-group">
                    <%= f.label :name%>
                    <%= f.text_field :name, class: "form-control"%>
                </div>

                <div class="form-label-group">
                    <%= f.label :corporate_name %>
                    <%= f.text_field :corporate_name, class: "form-control" %>
                </div>

                <div class="form-label-group">
                    <%= f.label :cnpj %>
                    <%= f.text_field :cnpj, class: "form-control" %>
                </div>

                <div class="form-label-group">
                    <%= f.label :address %>
                    <%= f.text_field :address, class: "form-control" %>
                </div>

                <div class="form-label-group">
                    <%= f.label :domain%>
                    <%= f.text_field :domain, class: "form-control"%>  
                </div>
                
                <div class="form-label-group actions">
                    <%= f.submit class: "btn btn-lg btn-primary btn-block text-uppercase" %>
                  </div>
              <% end %>
            </div>
            </div>
        </div>
  </div>     
</body>

app/views/home/index.html.erb
<h1> Welcome </h1>


<% if user_signed_in? == false %>
  <%= link_to 'Sign_in', new_user_session_path, class: "nav-link" %>
  <%= link_to 'Signup', new_user_registration_path, class: "nav-link" %></li>
  <%= link_to 'New company', new_company_path %>
<% else %>
   Olá, <%= current_user.name %>
   <%= link_to 'Sign out', destroy_user_session_path, method: :delete %> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TabbsSw</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
      <div class="container">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <%= link_to root_path, class: "navbar-brand" do %>
              <%= image_tag "logo"%>
            <% end %>
          </li> 
        </ul>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? == false %>
              <li class="nav-item active">
                <%= link_to 'Sign_in', new_user_session_path, class: "nav-link" %>
              </li>
              <li class="nav-item active">
                <%= link_to 'Signup', new_user_registration_path, class: "nav-link" %>
              </li>
              <li class="nav-item active">
                <%= link_to 'New company', new_company_path, class: "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item active">
                <h5 class="nav-item active nav-link"> Olá, <%= current_user.name %> </h5>
              </li>
              <li class="nav-item active">
                <%= link_to 'New Post', new_post_path, class: "nav-link" %>
              </li>
              <li class="nav-item active">
                <%= link_to 'Edit account', edit_user_registration_path, class: "nav-link" %>
              </li>
              <li class="nav-item active">
                <%= link_to 'Admin_Area', rails_admin_path, class: "nav-link" %>
              </li>
              <li class="nav-item active">
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "nav-link" %>
              </li>
            <% end %>    
          </ul>
        </div>
      </div>
    </nav>
    <p class="text-center alert-danger"><%= alert %></p>
    <p class="notice text-center alert-success"><%= notice %></p>
    <div class="container">
      <%= yield %>
    </div>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/posts/index.html.erb
</br></br>
</br>
<hr>
<h5 class="card-title text-center text-light bg-dark">All Posts</h5>
<% @posts.each do |post| %>
  <div class="columns is-centered">
    <div class="column is-four-fifths">
      <div class="card">
        <div class="card-content">
          <div class="media">
            <div class="media-content">
              <a href="<%= post_path(id: post.id) %>"><p class="title is-4"><%= post.title %></p></a>
            </div>
          </div>
          <p><i class="fa fa-user"></i> Autor: <strong><%= post.user.name %></strong></p>
          <p><i class="fa fa-clock"></i> Postado em: <strong><%= post.created_at.strftime("%d/%m/%Y") %></strong></p>
        </div>
      </div>
    </div>
  </div>
<% end %>
<%== pagy_bootstrap_nav(@pagy) %>

app/views/posts/new.html.erb
<% @post.errors.full_messages.each do |message|%>
    <ul>
        <ol class="text-center alert-danger"><%= message%></ol>
    </ul>
<%end%>

<%= form_with model: @post, local: true do |form|%>
<h5 class="card-title text-center text-light bg-dark">New Post</h5>

    <div class="form-label-group">
        <%= form.label :title%>
        <%= form.text_field :title, class: "form-control"%>
    </div>
    
    <div class="form-label-group">
        <%= form.label :body%>
        <%= form.text_area :body, class: "form-control"%>
    </div>
    
    <%= form.submit 'Post', class:"btn btn-primary"%>

<% end %>

app/views/posts/show.html.erb
<div class="container">
    <%= link_to posts_path, class: "button is-button is-link" do %>
        <i class="fa fa-arrow-left"></i> VOLTAR
    <% end %>
    <div class="columns">
        <div class="column">
            <p class="title text-center text-light bg-dark"><%= @post.title%></p>
        </div>
    </div>
    <div class="columns">
        <div class="column is-three-quarters"><h4><%= @post.body %></h4>
        <div class="column"><h6>Autor: <%= @post.user.name %></h6>
    </div></br>
    <p><div>
      <h5 class="card-title text-center">Comentários</h5>
    </div></p>
    
        <%= render partial: "comments/form", locals: { commentable: @post } %>
    
        
        <%= render @post.comments.where(parent_id: nil) %>
        
</div>